## Built in Functions

In [1]:
a, b, c = cos(0.2), log(10), abs(-1.22)

(0.9800665778412416, 2.302585092994046, 1.22)

In [2]:
a

0.9800665778412416

In [3]:
b

2.302585092994046

In [4]:
c

1.22

In [5]:
?cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos const close isconst



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


In [7]:
? help

search: schedule Channel @threadcall AbstractChannel searchsortedlast



**Welcome to Julia 1.0.3.** The full manual is available at

```
https://docs.julialang.org/
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [8]:
? hist

search: clear_history pushfirst! searchsortedfirst thisind pushdisplay

Couldn't find hist
Perhaps you meant hash, hcat, Cint, Dict, cis, first, last, isa, which or while


No documentation found.

Binding `hist` does not exist.


In [9]:
?size

search: size sizeof sizehint! Csize_t resize! filesize Cssize_t displaysize



```
size(A::AbstractArray, [dim])
```

Return a tuple containing the dimensions of `A`. Optionally you can specify a dimension to just get the length of that dimension.

Note that `size` may not be defined for arrays with non-standard indices, in which case [`axes`](@ref) may be useful. See the manual chapter on [arrays with custom indices](@ref man-custom-indices).

# Examples

```jldoctest
julia> A = fill(1, (2,3,4));

julia> size(A)
(2, 3, 4)

julia> size(A, 2)
3
```


In [10]:
exp(2)

7.38905609893065

In [11]:
log10(10)

1.0

In [12]:
ceil(5.76)

6.0

In [13]:
?rem

search: rem rem2pi baremodule divrem extrema reim IOStream precompile



```
rem(x::Integer, T::Type{<:Integer}) -> T
mod(x::Integer, T::Type{<:Integer}) -> T
%(x::Integer, T::Type{<:Integer}) -> T
```

Find `y::T` such that `x` ≡ `y` (mod n), where n is the number of integers representable in `T`, and `y` is an integer in `[typemin(T),typemax(T)]`. If `T` can represent any integer (e.g. `T == BigInt`), then this operation corresponds to a conversion to `T`.

# Examples

```jldoctest
julia> 129 % Int8
-127
```

---

```
rem(x, y)
%(x, y)
```

Remainder from Euclidean division, returning a value of the same sign as `x`, and smaller in magnitude than `y`. This value is always exact.

# Examples

```jldoctest
julia> x = 15; y = 4;

julia> x % y
3

julia> x == div(x, y) * y + rem(x, y)
true
```

---

```
rem(x, y, r::RoundingMode)
```

Compute the remainder of `x` after integer division by `y`, with the quotient rounded according to the rounding mode `r`. In other words, the quantity

```
x - y*round(x/y,r)
```

without any intermediate rounding.

  * if `r == RoundNearest`, then the result is exact, and in the interval $[-|y|/2, |y|/2]$. See also [`RoundNearest`](@ref).
  * if `r == RoundToZero` (default), then the result is exact, and in the interval $[0, |y|)$ if `x` is positive, or $(-|y|, 0]$ otherwise. See also [`RoundToZero`](@ref).
  * if `r == RoundDown`, then the result is in the interval $[0, y)$ if `y` is positive, or $(y, 0]$ otherwise. The result may not be exact if `x` and `y` have different signs, and `abs(x) < abs(y)`. See also[`RoundDown`](@ref).
  * if `r == RoundUp`, then the result is in the interval `(-y,0]` if `y` is positive, or `[0,-y)` otherwise. The result may not be exact if `x` and `y` have the same sign, and `abs(x) < abs(y)`. See also [`RoundUp`](@ref).


In [14]:
rem(15, 4)

3

In [15]:
15 % 4

3

In [16]:
?digits!

search: digits! digits ndigits isdigit isxdigit disable_sigint



```
digits!(array, n::Integer; base::Integer = 10)
```

Fills an array of the digits of `n` in the given base. More significant digits are at higher indices. If the array length is insufficient, the least significant digits are filled up to the array length. If the array length is excessive, the excess portion is filled with zeros.

# Examples

```jldoctest
julia> digits!([2,2,2,2], 10, base = 2)
4-element Array{Int64,1}:
 0
 1
 0
 1

julia> digits!([2,2,2,2,2,2], 10, base = 2)
6-element Array{Int64,1}:
 0
 1
 0
 1
 0
 0
```


In [17]:
digits!([2],3, base = 2)

1-element Array{Int64,1}:
 1

In [18]:
methods(muladd)

# 12 methods for generic function "muladd":
[1] muladd(a::Float16, b::Float16, c::Float16) in Base at float.jl:406
[2] muladd(x::Float64, y::Float64, z::Float64) in Base at float.jl:404
[3] muladd(x::Float32, y::Float32, z::Float32) in Base at float.jl:403
[4] muladd(z::Complex, w::Complex, x::Complex) in Base at complex.jl:271
[5] muladd(x::Real, z::Complex, y::Number) in Base at complex.jl:314
[6] muladd(z::Complex, x::Real, y::Real) in Base at complex.jl:315
[7] muladd(z::Complex, x::Real, w::Complex) in Base at complex.jl:316
[8] muladd(x::Real, y::Real, z::Complex) in Base at complex.jl:318
[9] muladd(z::Complex, w::Complex, x::Real) in Base at complex.jl:319
[10] muladd(x::T, y::T, z::T) where T<:Number in Base at promotion.jl:419
[11] muladd(x::Number, y::Number, z::Number) in Base at promotion.jl:348
[12] muladd(x, y, z) in Base.Math at math.jl:1011

In [19]:
methods(cos)

# 12 methods for generic function "cos":
[1] cos(x::BigFloat) in Base.MPFR at mpfr.jl:683
[2] cos(::Missing) in Base.Math at math.jl:1070
[3] cos(a::Complex{Float16}) in Base.Math at math.jl:1019
[4] cos(a::Float16) in Base.Math at math.jl:1018
[5] cos(z::Complex{T}) where T in Base at complex.jl:778
[6] cos(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:100
[7] cos(x::Real) in Base.Math at special/trig.jl:124
[8] cos(A::LinearAlgebra.Hermitian{#s575,S} where S<:(AbstractArray{#s576,2} where #s576<:#s575) where #s575<:Complex) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:720
[9] cos(A::Union{Hermitian{#s576,S}, Symmetric{#s576,S}} where S where #s576<:Real) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:716
[10] cos(D::LinearAlgebra.Diagonal) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/diagonal.jl:424
[11] cos(A::AbstractArray{#s576,2} where #s576<:Real) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:737
[12] cos(A::AbstractArray{#s576,2} where #s576<:Complex) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:744