## Functions

In [4]:
twentytimes(firstvar) = 20 * firstvar

twentytimes (generic function with 1 method)

In [5]:
typeof(twentytimes)

typeof(twentytimes)

In [6]:
twentytimes(10)

200

In [7]:
addxtoy(x, y) = x + y

addxtoy (generic function with 1 method)

In [8]:
addxtoy(3,4.5)

7.5

In [1]:
b24ac(a,b,c) = 
b^2 - 4 * a * c

b24ac (generic function with 1 method)

In [13]:
b24ac(1,4,34)

-120

In [14]:
function mytypeof(value)
    println("The type of $(value) is $(typeof(value))")
end

mytypeof (generic function with 1 method)

In [15]:
mytypeof(10)

The type of 10 is Int64


In [16]:
mytypeof(2.3)

The type of 2.3 is Float64


In [17]:
mytypeof(true)

The type of true is Bool


In [18]:
60 \ 5040

84.0

In [19]:
? \

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [20]:
addone(x::Int64) = x+1

addone (generic function with 1 method)

In [21]:
addone(10.)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[20]:1

In [22]:
addone(20*1.0)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[20]:1

In [23]:
addone(10)

11

In [24]:
addone(ceil(1.2)*10)

MethodError: MethodError: no method matching addone(::Float64)
Closest candidates are:
  addone(!Matched::Int64) at In[20]:1

In [25]:
a,b=1,2

(1, 2)

In [26]:
a,b=b,a

(2, 1)

In [27]:
function test(input)
  println("$input"^2)
end

test (generic function with 1 method)

In [28]:
test(2)

22


In [29]:
add2(x,y) = return x + y

add2 (generic function with 1 method)

In [30]:
println(add2(5, 7))

12


In [31]:
function add2(x,y) = x + y

LoadError: syntax: unexpected "="

In [32]:
add2(x,y) = x + y

add2 (generic function with 1 method)

In [33]:
println(add2(5, 7))

12


In [34]:
function coordinates(x, y=0, z=0)
  println("($x, $y, $z)")
end

coordinates (generic function with 3 methods)

In [35]:
coordinates(1, 2)

(1, 2, 0)


In [36]:
coordinates(1, 0)

(1, 0, 0)


In [37]:
coordinates(1, 0, 0)

(1, 0, 0)


In [38]:
coordinates(1, 0, 2)

(1, 0, 2)
